[project]
name = "wallet-project"
version = "0.1.0"
description = "A wallet project for learning"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.2",
    "djangorestframework>=3.16.1",
    "psycopg[binary]>=3.3.3",
    "requests>=2.32.5",
]
